coffee_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from .views import MyOrderView
from django.urls import path

urlpatterns = [
    path('my-order', MyOrderView.as_view(), name='my_order')
]

products/urls.py
from django.urls import path
from .views import ProductFormView
from .views import SuccessFormView

urlpatterns = [
    path('agregar', ProductFormView.as_view(), name='add_product'),
    path('', SuccessFormView.as_view(), name='list_product')
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView
from django.urls import path

urlpatterns = [
    path(
        'login',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout',
        LogoutView.as_view(),
        name='logout'
    ),
    path(
        'register',
        RegisterView.as_view(),
        name='register'
    ),
]

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    order_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"Order {self.id}  by {self.user.username}"
    
class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField()

    def __str__(self):
        return f"Order {self.order} - Product {self.product}"
    

products/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.TextField(max_length=200, verbose_name='nombre')
    description = models.TextField(max_length=300, verbose_name='descripcion')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='precio')
    available = models.BooleanField(default=True)
    photo = models.ImageField(upload_to='products', null=True, blank=True)
    calification = models.IntegerField(verbose_name='calificacion', null=True, blank=True)

    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.

products/forms.py
from django import forms
from django.forms import ModelForm
from .models import Product

class ProductForm(forms.Form):
    name = forms.CharField(max_length=200, label="Nombre")
    description = forms.CharField(max_length=300, label="Descripcion")
    price = forms.DecimalField(max_digits=10, decimal_places=2, label="Precio")
    available = forms.BooleanField(required=False, label="Disponible", initial=True)
    photo = forms.ImageField(required=False, label="Foto",)


    def save(self):
        Product.objects.create(
            name=self.cleaned_data['name'],
            description=self.cleaned_data['description'],
            price=self.cleaned_data['price'],
            available=self.cleaned_data['available'],
            photo=self.cleaned_data['photo'],
        )

orders/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Order
# Create your views here.
class MyOrderView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'orders/my_order.html'
    context_object_name = 'order'
    def get_object(self, queryset = None):
        return Order.objects.filter(is_active=True, user=self.request.user).first()

products/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .forms import ProductForm
from products.models import Product
# Create your views here.


class ProductFormView(generic.FormView):
    template_name = 'products/add_product.html'
    form_class = ProductForm
    success_url = reverse_lazy('list_product')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class SuccessFormView(generic.ListView):
    model = Product
    template_name = 'products/success.html'
    context_object_name = 'products'

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy 
# Create your views here.

class RegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('login')

orders/templates/orders/my_order.html
{% extends "base.html" %}

{% block content %}
<h1 class="text-3xl font-bold text-center text-gray-900 dark:text-white" style="margin: 5px;">Mis Pedidos</h1>
<article class="rounded-xl border border-gray-700 bg-gray-800 p-4 shadow-sm" style="max-width: 800px; margin: auto;">
    <div class="flex items-center gap-4">
      <img
        alt=""
        src="https://images.unsplash.com/photo-1614644147724-2d4785d69962?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=928&q=80"
        class="size-16 rounded-full object-cover hidden"
      />
  
      <div>
        <h3 class="text-lg font-medium text-white">{{ order.user.username }}</h3>
  
        <div class="flow-root">
          <ul class="-m-1 flex flex-wrap">
            <li class="p-1 leading-none">
              <a href="#" class="text-xs font-medium text-gray-300">{{ order.order_date }}</a>
            </li>
  
            <li class="hidden p-1 leading-none">
              <a href="#" class="text-xs font-medium text-gray-300"> GitHub </a>
            </li>
  
            <li class="hidden p-1 leading-none">
              <a href="#" class="text-xs font-medium text-gray-300">Website</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  
    <ul class="mt-4 space-y-2">
      {% for product_order in order.orderproduct_set.all %}
      <li style="margin: 5px;">
        <a href="#" class="block h-full rounded-lg border border-gray-700 p-4 hover:border-pink-600">
          <strong class="font-medium text-white">{{ product_order.product.name }}</strong>
  
          <p class="mt-1 text-xs font-medium text-gray-300">
            <strong>Precio:</strong> {{ product_order.product.price}} 
            <strong>Cantidad:</strong> {{ product_order.quantity }} 
          </p>
        </a>
      </li>
      {% empty %}
        No hay productos en este pedido
      {% endfor %}
    </ul>
  </article>

<!-- {% debug order %} -->
{% endblock content %}

products/templates/products/add_product.html
{% extends "base.html" %}

{% block content %}
<form action="{% url "add_product" %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Agregar</button>
</form>
{% endblock %}

products/templates/products/success.html
{% extends "base.html" %}

{% block content %}
<h1 class="text-3xl font-bold text-center text-gray-900 dark:text-white" >Lista de Productos</h1>

<ul style="list-style: none; display: flex; flex-wrap: wrap; gap: 1rem; justify-content: center;">
    {% for product in products %}
        <li>
            <a href="#" class="block rounded-lg p-4 shadow-xs shadow-indigo-100" style="max-width: 300px;">
                <img
                  alt=""
                  src="{{ product.photo.url }}"
                  class="h-56 w-full rounded-md object-cover"
                />
              
                <div class="mt-2">
                  <dl>
                    <div>
                      <dt class="sr-only">Price</dt>
              
                      <dd class="text-sm text-gray-500">${{product.price}}</dd>
                    </div>
              
                    <div>
                      <dt class="sr-only">Address</dt>
              
                      <dd class="font-medium">{{product.name}}</dd>
                    </div>
                  </dl>
              
                  <div class="mt-6 flex items-center gap-8 text-xs">
                    <div class="sm:inline-flex sm:shrink-0 sm:items-center sm:gap-2">
                      <svg
                        class="size-4 text-indigo-700"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          stroke-width="2"
                          d="M8 14v3m4-3v3m4-3v3M3 21h18M3 10h18M3 7l9-4 9 4M4 10h16v11H4V10z"
                        />
                      </svg>
              
                      <div class="mt-1.5 sm:mt-0">
                        <p class="text-gray-500">Parking</p>
              
                        <p class="font-medium">2 spaces</p>
                      </div>
                    </div>
              
                    <div class="sm:inline-flex sm:shrink-0 sm:items-center sm:gap-2">
                      <i class="bi bi-star-fill text-indigo-700"></i>
              
                      <div class="mt-1.5 sm:mt-0">
                        <p class="text-gray-500">Calificacion</p>
              
                        <p class="font-medium">{{ product.calification }}</p>
                      </div>
                    </div>
              
                    <div class="sm:inline-flex sm:shrink-0 sm:items-center sm:gap-2">
                      <svg
                        class="size-4 text-indigo-700"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          stroke-width="2"
                          d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"
                        />
                      </svg>
              
                      <div class="mt-1.5 sm:mt-0">
                        <p class="text-gray-500">Bedroom</p>
              
                        <p class="font-medium">4 rooms</p>
                      </div>
                    </div>
                  </div>
                </div>
              </a>
        </li>
        <!-- <li>
            {{ product.name }}
            <p>{{ product.price }}</p>
            {% if product.photo %}
                <img src="{{ product.photo.url }}" alt="{{ product.name }}" style="max-height: 100px;">
            {% endif %}
        </li> -->
    {% endfor %}
</ul>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <title>Coffee Shop</title>
</head>
<body>
    <header class="bg-white">
        <div class="mx-auto max-w-screen-xl px-4 sm:px-6 lg:px-8">
          <div class="flex h-16 items-center justify-between">
            <div class="md:flex md:items-center md:gap-12">
              <a class="block text-teal-600" href="#">
                <span class="sr-only" >Home</span>
                <i class="bi bi-cup-hot-fill" style="font-size: 30px;"></i>
              </a>
            </div>
      
            <div class="hidden md:block">
              <nav aria-label="Global">
                <ul class="flex items-center gap-6 text-sm">
                  <li>
                    <a class="text-gray-500 transition hover:text-gray-500/75" href="#"> About </a>
                  </li>
      
                  <li>
                    <a class="text-gray-500 transition hover:text-gray-500/75" href="#"> Careers </a>
                  </li>
      
                  <li>
                    <a class="text-gray-500 transition hover:text-gray-500/75" href="#"> History </a>
                  </li>
      
                  <li>
                    <a class="text-gray-500 transition hover:text-gray-500/75" href="#"> Services </a>
                  </li>
      
                  <li>
                    <a class="text-gray-500 transition hover:text-gray-500/75" href="#"> Projects </a>
                  </li>
      
                  <li>
                    <a class="text-gray-500 transition hover:text-gray-500/75" href="#"> Blog </a>
                  </li>
                </ul>
              </nav>
            </div>
            <div class="flex items-center gap-4">
              {% if user.is_authenticated %}
              <div class="sm:flex sm:gap-4" style="display: flex; align-items: center;">
                <p style="margin: 8px;">Hola, {{ user.username }}!</p>
                <form action="{% url 'logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="rounded-md bg-teal-600 px-5 py-2.5 text-sm font-medium text-white shadow-sm">
                    Logout
                  </button>
                </form>
              </div>
              {% else %}
              <div class="sm:flex sm:gap-4">
                <a
                  class="rounded-md bg-teal-600 px-5 py-2.5 text-sm font-medium text-white shadow-sm"
                  href="{% url 'login' %}"
                >
                  Login
                </a>

                </div>
                {% endif %}
                <div class="sm:flex">
                    <a
                      class="rounded-md bg-gray-100 px-5 py-2.5 text-sm font-medium text-teal-600"
                      href="{% url 'my_order' %}"
                    >
                      Mi pedido
                    </a>
                  </div>
              <div class="block hidden">
                <button
                  class="rounded-sm bg-gray-100 p-2 text-gray-600 transition hover:text-gray-600/75"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="size-5"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    stroke-width="2"
                  >
                    <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </div>
      </header>
    <!-- Hola,
    {% if user.is_authenticated %}
        {{ user.username }}!
        <form action="{% url "logout" %}" method="post">
            {% csrf_token %}
            <button type="submit" class="">Cerrar sesión</button>
        </form>
    {% else %}
        Invitado! <a href="{% url "login" %}">Login</a>
    {% endif %} -->
    <div class="container mx-auto px-4">
        {% block content %}{% endblock content %}
    </div>
</body>
</html>

users/templates/users/login.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<h1 class="text-3xl font-bold text-center text-gray-900 dark:text-white">Iniciar sesión</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button
        class="inline-block rounded-sm bg-indigo-600 px-8 py-3 text-sm font-medium text-white transition hover:scale-110 hover:shadow-xl focus:ring-3 focus:outline-hidden"
        href="#"
        type="submit"
    >
        Iniciar sesión
    </button>
</form>
<p style="margin: 8px;">No tienes una cuenta?, <a href="{% url 'register' %}" style="text-decoration: underline;">Registrate</a></p>
{% endblock content %}

users/templates/users/register.html
{% extends 'base.html' %}

{% load tailwind_filters %}
{% block content %}
<h1 class="text-3xl font-bold text-center text-gray-900 dark:text-white">Registro</h1>
<form method="post" class="max-w-md mx-auto p-8 bg-white rounded-lg shadow md:p-12 lg:p-16 xl:p-20">
    {% csrf_token %}
    {{ form|crispy }}
    <button
        class="inline-block rounded-sm bg-indigo-600 px-8 py-3 text-sm font-medium text-white transition hover:scale-110 hover:shadow-xl focus:ring-3 focus:outline-hidden"
        type="submit"
    >
        Registrarse
    </button>
    <p class="mt-4 text-center text-sm text-gray-500">
        ¿Ya tienes una cuenta? <a href="{% url 'login' %}" class="text-indigo-600 hover:underline">Inicia sesión</a>
    </p>
</form>
{% endblock %}